force-app/main/default/objects/ER_Store__c/ER_Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ER_Store__c/fields/ER_Merchant__c.field-meta.xml
<CustomField>
    <fullName>ER_Merchant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Merchant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stores</relationshipLabel>
    <relationshipName>Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LNER01_StoreCreation_Test.cls
@isTest
public class LNER01_StoreCreation_Test {

        @isTest static void testMagicStoreController() {
        
        //getAccount    
        Account testAccount = new Account();
 		testAccount.Name='Test Account' ;
 		insert testAccount;
            
        Account newAccount = LNER01_StoreCreation.getAccountWS(testAccount.Id);
        System.assertEquals('Test Account', newAccount.Name);
            
        //saveStoreFromAccount    
        ER_Store__c testErStore = new ER_Store__c();
        testErStore.ER_Merchant__c = newAccount.Id; 
        testErStore.Name = 'Test Store';
            
        ER_Store__c newErStore = LNER01_StoreCreation.saveStoreWS(testErStore, newAccount.Id);
        System.assertEquals('Test Store',newErStore.Name);
    }
}