force-app/main/default/objects/ER_Store__c/ER_Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ER_Store__c/fields/ER_Merchant__c.field-meta.xml
<CustomField>
    <fullName>ER_Merchant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Merchant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stores</relationshipLabel>
    <relationshipName>Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LNER01_StoreCreation.cls
//MagicStoreController
public with sharing class LNER01_StoreCreation {

    @AuraEnabled
    public static Account getAccountWS(Id accId) {
        return [SELECT Name, BillingStreet, BillingPostalCode, BillingCity FROM Account WHERE Id = :accId];
    }
    
    @AuraEnabled
    //ER_Store__c
    public static ER_Store__c saveStoreWS(ER_Store__c erStore, Id accId) {
        
        erStore.ER_Merchant__c = accId;
        upsert erStore;
        //return erStore.Id;
        return erStore;
    }
}