force-app/main/default/objects/ER_Contract__c/ER_Contract__c.object-meta.xml
<CustomObject>
    <label>Contract (Edenred)</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ER_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ER_Contract__c/fields/Contract_end_date__c.field-meta.xml
<CustomField>
    <fullName>Contract_end_date__c</fullName>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ER_Contract__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CreateAccountandContractTestClass.cls
@isTest
public class CreateAccountandContractTestClass {
  static testMethod void CreateAccountandContract(){
                //Create an Account
        Account a = new Account(Name='Test Account', OwnerId ='0050Y000001IPL8', Inactive_Reason__c = 'Mitbewerber');
        System.debug('Name before inserting new account: ' + a.Name);
                //Insert Account
        insert a;
                //Create an active contract
                ER_Contract__c z = new ER_Contract__c(Account_Name__c=a.Id, Contract_Start_Date__c  = system.TODAY()-10);
                insert z;
                //Create a second inactive contract
                ER_Contract__c y = new ER_Contract__c(Account_Name__c=a.Id, Contract_Start_Date__c   = system.TODAY()-10, Contract_end_date__c = system.today()-9);
                //insert y;
                //Change active contract to inactive
                z.Contract_end_date__c = system.TODAY()-1;
                            update z;
                }
                }