force-app/main/default/objects/ER_Contract__c/ER_Contract__c.object-meta.xml
<CustomObject>
    <label>Contract (Edenred)</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ER_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ER_Contract__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <label>Advisor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andrea Krakolinig</fullName>
            </value>
            <value>
                <fullName>Andrea Mader</fullName>
            </value>
            <value>
                <fullName>Andreas Hübner</fullName>
            </value>
            <value>
                <fullName>Barbara Kreuzberger</fullName>
            </value>
            <value>
                <fullName>Barbara Pillitsch</fullName>
            </value>
            <value>
                <fullName>bestehender Kunde</fullName>
            </value>
            <value>
                <fullName>Brandic Igor</fullName>
            </value>
            <value>
                <fullName>Celine Vernet</fullName>
            </value>
            <value>
                <fullName>Christiane Bichlbauer</fullName>
            </value>
            <value>
                <fullName>Christos Laki</fullName>
            </value>
            <value>
                <fullName>Cornelia Kuchar</fullName>
            </value>
            <value>
                <fullName>Ehemalige Mitarbeiter</fullName>
            </value>
            <value>
                <fullName>El Mohandes</fullName>
            </value>
            <value>
                <fullName>Gabor Nyul</fullName>
            </value>
            <value>
                <fullName>Ganthaler Sebastian</fullName>
            </value>
            <value>
                <fullName>Gerhard Leeb</fullName>
            </value>
            <value>
                <fullName>Gert Tuppinger</fullName>
            </value>
            <value>
                <fullName>Harald Pohl</fullName>
            </value>
            <value>
                <fullName>Jürgen Maier</fullName>
            </value>
            <value>
                <fullName>Karin Berger</fullName>
            </value>
            <value>
                <fullName>Katharina Lechner</fullName>
            </value>
            <value>
                <fullName>Kathrin Partl</fullName>
            </value>
            <value>
                <fullName>Margareta Dyga</fullName>
            </value>
            <value>
                <fullName>Martin Motovsky</fullName>
            </value>
            <value>
                <fullName>Martin Raudaschl</fullName>
            </value>
            <value>
                <fullName>Martin Rettenbacher</fullName>
            </value>
            <value>
                <fullName>Mergenthaler Rudolf</fullName>
            </value>
            <value>
                <fullName>Monika Hoegl</fullName>
            </value>
            <value>
                <fullName>Nadine Koppel</fullName>
            </value>
            <value>
                <fullName>Nadine Köppel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ER_Contract__c/fields/AT_Comments__c.field-meta.xml
<CustomField>
    <fullName>AT_Comments__c</fullName>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ER_Contract__c/fields/Commission_Value__c.field-meta.xml
<CustomField>
    <fullName>Commission_Value__c</fullName>
    <label>Commission Value</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ER_Contract__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ER_Contract__c/fields/Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Electronic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ER_Contract__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ER_Contract__c/recordTypes/Affiliate_Contract_RT.recordType-meta.xml
<RecordType>
    <fullName>Affiliate_Contract_RT</fullName>
    <active>true</active>
    <label>Affiliate Contract</label>
</RecordType>

force-app/main/default/objects/ER_Order__c/ER_Order__c.object-meta.xml
<CustomObject>
    <label>Order (Edenred)</label>
    <nameField>
        <displayFormat>OR-{0000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ER_Order__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ER_Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>IF(
   NOT(ISBLANK( ERAT_BillableService__c )),
    ERAT_BillableService__r.Name ,

CASE(Product_Code__c,
&quot;1&quot;, &quot;Ticket Service&quot;,
&quot;2&quot;, &quot;Ticket Compliments&quot;,
&quot;3&quot;, &quot;Ticket Restaurant&quot;, 
&quot;4&quot;, &quot;Wellness Gutschein&quot;, 
&quot;5&quot;, &quot;Ticket Junior&quot;,
&quot;6&quot;, &quot;Ticket Shopping&quot;,
&quot;7&quot;, &quot;Ticket Service Card&quot;,
&quot;8&quot;, &quot;Ticket Restaurant Card&quot;,
&quot;&quot;)
)</formula>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ER_Order__c/recordTypes/Affiliate_Order_RT.recordType-meta.xml
<RecordType>
    <fullName>Affiliate_Order_RT</fullName>
    <active>true</active>
    <label>Affiliate Order</label>
</RecordType>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Couponing Online</fullName>
    </customValue>
    <customValue>
        <fullName>Couponing Online+Print</fullName>
    </customValue>
    <customValue>
        <fullName>Couponing Online+Print+Merchant of the month</fullName>
    </customValue>
    <customValue>
        <fullName>Couponing Print</fullName>
    </customValue>
    <customValue>
        <fullName>FOOD</fullName>
        <label>FOOD Contract</label>
    </customValue>
    <customValue>
        <fullName>Merchant of the month</fullName>
    </customValue>
    <customValue>
        <fullName>No Product</fullName>
    </customValue>
    <customValue>
        <fullName>Paper contract Ticket Compliments</fullName>
    </customValue>
    <customValue>
        <fullName>Paper contract Ticket Junior</fullName>
    </customValue>
    <customValue>
        <fullName>Paper contract TR+TS+TC</fullName>
    </customValue>
    <customValue>
        <fullName>Paper contract TS+TC</fullName>
    </customValue>
    <customValue>
        <fullName>TC Card and Voucher new merchants</fullName>
    </customValue>
    <customValue>
        <fullName>TC Card and Voucher new merchants - chains</fullName>
    </customValue>
    <customValue>
        <fullName>TC Card current merchants</fullName>
    </customValue>
    <customValue>
        <fullName>TC Card current merchants - chains</fullName>
    </customValue>
    <customValue>
        <fullName>TC Card new merchants</fullName>
    </customValue>
    <customValue>
        <fullName>TC Card new merchants - chains</fullName>
    </customValue>
    <customValue>
        <fullName>Ticket Compliments</fullName>
    </customValue>
    <customValue>
        <fullName>Ticket Compliments Card</fullName>
    </customValue>
    <customValue>
        <fullName>Ticket Restaurant</fullName>
    </customValue>
    <customValue>
        <fullName>Ticket Restaurant Card</fullName>
    </customValue>
    <customValue>
        <fullName>Ticket Service</fullName>
    </customValue>
    <customValue>
        <fullName>Ticket Service Card</fullName>
    </customValue>
    <customValue>
        <fullName>TR+TC Cards and Vouchers new merchants</fullName>
    </customValue>
    <customValue>
        <fullName>TR+TC Cards and Vouchers new merchants - chains</fullName>
    </customValue>
    <customValue>
        <fullName>TR+TC Cards current merchants</fullName>
    </customValue>
    <customValue>
        <fullName>TR+TC Cards current merchants - chains</fullName>
    </customValue>
    <customValue>
        <fullName>TR+TC Cards new merchants</fullName>
    </customValue>
    <customValue>
        <fullName>TR+TC Cards new merchants - chains</fullName>
    </customValue>
    <customValue>
        <fullName>TR+TS+TC Cards and Vouchers new merchants</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TRTA05_Account_After_Update_TEST.cls
@isTest
public class TRTA05_Account_After_Update_TEST {
@isTest static void UpdateAccountOwner() 
	{
    	Profile adminp = [select id from profile where Name = 'System Administrator' limit 1];    
		List<User> lstUser = new list<User>();
        User adminu = new User(alias = 'test123', email='test1234@noemail.com', lastname='Testing', emailencodingkey='ISO-8859-1',localesidkey='fr_FR_EURO', languagelocalekey='fr', profileid = adminp.Id, timezonesidkey='Europe/Paris', username='test1235334'+String.valueOf(date.today())+ '@noemail.com', street='mystree', city='mycity', postalcode='1234', country='France');
		lstUser.add(adminu);
        User adminu2 = new User(alias = 'test1234', email='test12345@noemail.com', lastname='Testing2', emailencodingkey='ISO-8859-1',localesidkey='fr_FR_EURO', languagelocalekey='fr', profileid = adminp.Id, timezonesidkey='Europe/Paris', username='test12353345'+String.valueOf(date.today())+ '@noemail.com', street='mystreee', city='mycity2', postalcode='12345', country='France');
        lstUser.add(adminu2);
        insert lstUser; 
        Account acc = new Account(ownerid=adminu.id,recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Merchant_Account_RT').getRecordTypeId(), Name = 'AccTestTRAT',Partner_Code__c='TST-XX99');
		insert acc;
        Contact ContactAcc = new Contact(ownerid=adminu.id,FirstName = 'FirstName' , LastName = 'LastName',Email ='testemail@teeeeeeest.com', Accountid = acc.id );
		insert ContactAcc;
        ER_Contract__c contracttest = new ER_Contract__c(ownerid=adminu.id,Account_Name__c  = acc.id,recordtypeid = Schema.SObjectType.ER_Contract__c.getRecordTypeInfosByDeveloperName().get('Affiliate_Contract_RT').getRecordTypeId(),Advisor__c = 'Claudia Eisl',Commission_Value__c = 5.55,Product__c = 'Ticket Restaurant',Contract_Start_Date__c = date.today()-10,Invoice_Type__c = 'Electronic',AT_Comments__c = 'Comments'); 
		insert contracttest;
        ER_Order__c Ordertest = new ER_Order__c(ownerid=adminu.id,Account_Name__c= acc.id , recordtypeid = Schema.SObjectType.ER_Order__c.getRecordTypeInfosByDeveloperName().get('Affiliate_Order_RT').getRecordTypeId());  
		insert Ordertest;
        acc.ownerid = adminu2.id;
        update acc;    
	}
}