force-app/main/default/objects/ER_Acceptor__c/ER_Acceptor__c.object-meta.xml
<CustomObject>
    <label>Acceptor</label>
    <nameField>
        <label>Acceptor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acceptors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ER_Acceptor__c/fields/ER_MID_Authorization__c.field-meta.xml
<CustomField>
    <fullName>ER_MID_Authorization__c</fullName>
    <label>MID Authorization</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ER_Acceptor__c/fields/ER_Store__c.field-meta.xml
<CustomField>
    <fullName>ER_Store__c</fullName>
    <label>Store</label>
    <referenceTo>ER_Store__c</referenceTo>
    <relationshipLabel>Acceptors</relationshipLabel>
    <relationshipName>Acceptors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ER_Contract__c/ER_Contract__c.object-meta.xml
<CustomObject>
    <label>Contract (Edenred)</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ER_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ER_Contract__c/fields/Advisor__c.field-meta.xml
<CustomField>
    <fullName>Advisor__c</fullName>
    <label>Advisor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Andrea Krakolinig</fullName>
            </value>
            <value>
                <fullName>Andrea Mader</fullName>
            </value>
            <value>
                <fullName>Andreas Hübner</fullName>
            </value>
            <value>
                <fullName>Barbara Kreuzberger</fullName>
            </value>
            <value>
                <fullName>Barbara Pillitsch</fullName>
            </value>
            <value>
                <fullName>bestehender Kunde</fullName>
            </value>
            <value>
                <fullName>Brandic Igor</fullName>
            </value>
            <value>
                <fullName>Celine Vernet</fullName>
            </value>
            <value>
                <fullName>Christiane Bichlbauer</fullName>
            </value>
            <value>
                <fullName>Christos Laki</fullName>
            </value>
            <value>
                <fullName>Cornelia Kuchar</fullName>
            </value>
            <value>
                <fullName>Ehemalige Mitarbeiter</fullName>
            </value>
            <value>
                <fullName>El Mohandes</fullName>
            </value>
            <value>
                <fullName>Gabor Nyul</fullName>
            </value>
            <value>
                <fullName>Ganthaler Sebastian</fullName>
            </value>
            <value>
                <fullName>Gerhard Leeb</fullName>
            </value>
            <value>
                <fullName>Gert Tuppinger</fullName>
            </value>
            <value>
                <fullName>Harald Pohl</fullName>
            </value>
            <value>
                <fullName>Jürgen Maier</fullName>
            </value>
            <value>
                <fullName>Karin Berger</fullName>
            </value>
            <value>
                <fullName>Katharina Lechner</fullName>
            </value>
            <value>
                <fullName>Kathrin Partl</fullName>
            </value>
            <value>
                <fullName>Margareta Dyga</fullName>
            </value>
            <value>
                <fullName>Martin Motovsky</fullName>
            </value>
            <value>
                <fullName>Martin Raudaschl</fullName>
            </value>
            <value>
                <fullName>Martin Rettenbacher</fullName>
            </value>
            <value>
                <fullName>Mergenthaler Rudolf</fullName>
            </value>
            <value>
                <fullName>Monika Hoegl</fullName>
            </value>
            <value>
                <fullName>Nadine Koppel</fullName>
            </value>
            <value>
                <fullName>Nadine Köppel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ER_Contract__c/fields/Commission_Value__c.field-meta.xml
<CustomField>
    <fullName>Commission_Value__c</fullName>
    <label>Commission Value</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ER_Contract__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ER_Contract__c/fields/Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paper</fullName>
            </value>
            <value>
                <fullName>Electronic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ER_Contract__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ER_Contract__c/recordTypes/Affiliate_Contract_RT.recordType-meta.xml
<RecordType>
    <fullName>Affiliate_Contract_RT</fullName>
    <active>true</active>
    <label>Affiliate Contract</label>
</RecordType>

force-app/main/default/objects/ER_Loop__c/ER_Loop__c.object-meta.xml
<CustomObject>
    <label>Loop</label>
    <nameField>
        <label>Loop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loops</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ER_Loop__c/fields/ER_Reference__c.field-meta.xml
<CustomField>
    <fullName>ER_Reference__c</fullName>
    <externalId>true</externalId>
    <label>Reference</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ER_Store__c/ER_Store__c.object-meta.xml
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ER_Store__c/fields/AT_Accepts_Payment__c.field-meta.xml
<CustomField>
    <fullName>AT_Accepts_Payment__c</fullName>
    <label>Accepts Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Voucher only</fullName>
            </value>
            <value>
                <fullName>Card only</fullName>
            </value>
            <value>
                <fullName>Voucher+Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ER_Store__c/fields/AT_Category__c.field-meta.xml
<CustomField>
    <fullName>AT_Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Essen &amp; Ernährung</fullName>
                <default>true</default>
                <label>Essen &amp; Ernährung</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ER_Store__c/fields/AT_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>AT_Sub_Category__c</fullName>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>AT_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baumärkte</fullName>
            </value>
            <value>
                <fullName>Bekleidung</fullName>
            </value>
            <value>
                <fullName>Bio-Markt/Reformhaus</fullName>
            </value>
            <value>
                <fullName>Buchhandel</fullName>
            </value>
            <value>
                <fullName>Büroartikel</fullName>
            </value>
            <value>
                <fullName>Café &amp; Bäckerei</fullName>
            </value>
            <value>
                <fullName>Drogerie &amp; Pafümerie</fullName>
            </value>
            <value>
                <fullName>Elektronik</fullName>
            </value>
            <value>
                <fullName>Erlebnis &amp; Reisen</fullName>
            </value>
            <value>
                <fullName>Ernährungsprogramme</fullName>
            </value>
            <value>
                <fullName>Fast Food</fullName>
            </value>
            <value>
                <fullName>Feinkost &amp; Spezialitäten</fullName>
            </value>
            <value>
                <fullName>Fitnesscenter</fullName>
            </value>
            <value>
                <fullName>Haushaltswaren</fullName>
            </value>
            <value>
                <fullName>Imbiss &amp; Buffets</fullName>
            </value>
            <value>
                <fullName>Kfz Händler/Reparatur</fullName>
            </value>
            <value>
                <fullName>Kino</fullName>
            </value>
            <value>
                <fullName>Lieferdienste</fullName>
            </value>
            <value>
                <fullName>Metzgerei/Fleischerei</fullName>
            </value>
            <value>
                <fullName>Mietwagenservice</fullName>
            </value>
            <value>
                <fullName>Möbelhäuser</fullName>
            </value>
            <value>
                <fullName>Optiker</fullName>
            </value>
            <value>
                <fullName>Psychotherapeut</fullName>
            </value>
            <value>
                <fullName>Restaurants</fullName>
            </value>
            <value>
                <fullName>Schmuck</fullName>
            </value>
            <value>
                <fullName>Schuhmode</fullName>
            </value>
            <value>
                <fullName>Skigebiete</fullName>
            </value>
            <value>
                <fullName>Spielwaren &amp; Geschenkartikel</fullName>
            </value>
            <value>
                <fullName>Sportartikelanbieter</fullName>
            </value>
            <value>
                <fullName>Supermarkt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ER_Store__c/fields/ER_Merchant__c.field-meta.xml
<CustomField>
    <fullName>ER_Merchant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Merchant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stores</relationshipLabel>
    <relationshipName>Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Couponing Online</fullName>
    </customValue>
    <customValue>
        <fullName>Couponing Online+Print</fullName>
    </customValue>
    <customValue>
        <fullName>Couponing Online+Print+Merchant of the month</fullName>
    </customValue>
    <customValue>
        <fullName>Couponing Print</fullName>
    </customValue>
    <customValue>
        <fullName>FOOD</fullName>
        <label>FOOD Contract</label>
    </customValue>
    <customValue>
        <fullName>Merchant of the month</fullName>
    </customValue>
    <customValue>
        <fullName>No Product</fullName>
    </customValue>
    <customValue>
        <fullName>Paper contract Ticket Compliments</fullName>
    </customValue>
    <customValue>
        <fullName>Paper contract Ticket Junior</fullName>
    </customValue>
    <customValue>
        <fullName>Paper contract TR+TS+TC</fullName>
    </customValue>
    <customValue>
        <fullName>Paper contract TS+TC</fullName>
    </customValue>
    <customValue>
        <fullName>TC Card and Voucher new merchants</fullName>
    </customValue>
    <customValue>
        <fullName>TC Card and Voucher new merchants - chains</fullName>
    </customValue>
    <customValue>
        <fullName>TC Card current merchants</fullName>
    </customValue>
    <customValue>
        <fullName>TC Card current merchants - chains</fullName>
    </customValue>
    <customValue>
        <fullName>TC Card new merchants</fullName>
    </customValue>
    <customValue>
        <fullName>TC Card new merchants - chains</fullName>
    </customValue>
    <customValue>
        <fullName>Ticket Compliments</fullName>
    </customValue>
    <customValue>
        <fullName>Ticket Compliments Card</fullName>
    </customValue>
    <customValue>
        <fullName>Ticket Restaurant</fullName>
    </customValue>
    <customValue>
        <fullName>Ticket Restaurant Card</fullName>
    </customValue>
    <customValue>
        <fullName>Ticket Service</fullName>
    </customValue>
    <customValue>
        <fullName>Ticket Service Card</fullName>
    </customValue>
    <customValue>
        <fullName>TR+TC Cards and Vouchers new merchants</fullName>
    </customValue>
    <customValue>
        <fullName>TR+TC Cards and Vouchers new merchants - chains</fullName>
    </customValue>
    <customValue>
        <fullName>TR+TC Cards current merchants</fullName>
    </customValue>
    <customValue>
        <fullName>TR+TC Cards current merchants - chains</fullName>
    </customValue>
    <customValue>
        <fullName>TR+TC Cards new merchants</fullName>
    </customValue>
    <customValue>
        <fullName>TR+TC Cards new merchants - chains</fullName>
    </customValue>
    <customValue>
        <fullName>TR+TS+TC Cards and Vouchers new merchants</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LNAT01_StoreManager_TEST.cls
// StoreAuthorization depends on APAT01_ToolkitAT class and triggers, which needs to be in place for the tests to succeed.
// Removing assertion on StoreAuthorization is possible
//
@IsTest
public class LNAT01_StoreManager_TEST {
    
    

    @TestSetup
    static void makeData(){
    System.Debug('>>>    #START - LNAT01_StoreManager_TEST.MakeData \r\n');

    List<ER_Loop__c> apmLoops = new List<ER_Loop__c>();
    apmLoops.add(new ER_Loop__c(Name='APM_TR', ER_Reference__c='LOOP-0001'));
    apmLoops.add(new ER_Loop__c(Name='APM_TS', ER_Reference__c='LOOP-0002'));
    insert apmLoops;


    List<Account> accs = new List<Account>();
    accs.add(new Account(Name='UnitTest Merchant CT00', Partner_Code__c='MER-CT00', RecordTypeId=APAT01_ToolkitAT.GetRecordTypeId('Account','Merchant_Account_RT')));              //Vouchers + Cards - standard client
    accs.add(new Account(Name='UnitTest Merchant CT01', Partner_Code__c='MER-CT01', RecordTypeId=APAT01_ToolkitAT.GetRecordTypeId('Account','Merchant_Account_RT')));      //have 2 active contracts
  
    insert accs;

    System.debug('TEST.DATAPREP: INSERTED Account: ' + accs.size());

        ER_Contract__c c = new ER_Contract__c();

        c.Account_Name__c  = accs[1].Id;
        c.Product__c = 'Ticket Restaurant Card';
        c.RecordTypeId = Schema.getGlobalDescribe().get('ER_Contract__c').getDescribe().getRecordTypeInfosByDeveloperName().get('Affiliate_Contract_RT').getRecordTypeId();
        c.Advisor__c = 'Claudia Eisl';
        c.Commission_Value__c = 5.55;
        c.Contract_Start_Date__c = date.today()-10;         
        c.Invoice_Type__c = 'Electronic';
        insert c;



    //Stores

    List<ER_Store__c> stores = new List<ER_Store__c>();
    
    stores.add (new ER_Store__c(Name='Test Store MER-CT01 - Voucher only',   AT_Accepts_Payment__c='Voucher only', AT_Category__c = 'Essen & Ernährung', AT_Sub_Category__c = 'Supermarkt', ER_Merchant__c = accs[1].id) );
    stores.add (new ER_Store__c(Name='Test Store MER-CT01 - Vouher+Card',    AT_Accepts_Payment__c='Voucher+Card', AT_Category__c = 'Essen & Ernährung', AT_Sub_Category__c = 'Supermarkt', ER_Merchant__c = accs[1].id) );
    stores.add (new ER_Store__c(Name='Test Store MER-CT01 - Card only',      AT_Accepts_Payment__c='Card only', AT_Category__c = 'Essen & Ernährung', AT_Sub_Category__c = 'Supermarkt', ER_Merchant__c = accs[1].id) );
    stores.add (new ER_Store__c(Name='Test Store MER-CT01 - None',           AT_Accepts_Payment__c='Card only', AT_Category__c = 'Essen & Ernährung', AT_Sub_Category__c = 'Supermarkt', ER_Merchant__c = accs[1].id) );
    
    insert stores;
    //Acceptors

    List<ER_Acceptor__c> acceptors = new List<ER_Acceptor__c>();
    for (ER_Store__c store : stores) {
        acceptors.add (new ER_Acceptor__c(Name='Test Acceptor MER-CT01', ER_Store__c=store.Id, ER_MID_Authorization__c = String.valueof(store.Id)) );
    }

    insert acceptors;
    
    // obtain gobal Test Account Id
    

    System.Debug('');
    System.Debug('<<<    #FINISHED - APAT01_ToolkitAT_Test.MakeData \r\n');
    System.Debug('');
    }

    @IsTest 
    public static void GetCounters() {
        
        Id accId  = [SELECT Id FROM Account WHERE Partner_code__c='MER-CT01' LIMIT 1][0].Id;

        List<Integer> recCounters = LNAT01_StoreManager.GetCounters(accId); // result contains: Store, Acceptor, StoreAuth
        system.assertEquals(4, recCounters[0], 'Check Store count');
        system.assertEquals(4, recCounters[1], 'Check Acceptor count');
        system.assertEquals(8, recCounters[2], 'Check StoreAuth count');

        try {
            recCounters = LNAT01_StoreManager.GetCounters('0010Q00000zzzzzzzz');
        } catch (exception e) {
            system.assert(e.getMessage().contains('Unable to execut query'),'Confirm exception');
        }

    }
    @IsTest 
    public static void deleteUnderlyingAcceptorsAndStores(){
        Id accId  = [SELECT Id FROM Account WHERE Partner_code__c='MER-CT01' LIMIT 1][0].Id;

        LNAT01_StoreManager.deleteUnderlyingAcceptorsAndStores(accId);

        List<Integer> recCounters = LNAT01_StoreManager.GetCounters(accId); // result contains: Store, Acceptor, StoreAuth
        system.assertEquals(0, recCounters[0], 'Check Store count');
        system.assertEquals(0, recCounters[1], 'Check Acceptor count');
        system.assertEquals(0, recCounters[2], 'Check StoreAuth count');

        try{
            LNAT01_StoreManager.deleteUnderlyingAcceptorsAndStores('0010Q00000zzzzzzzz'); //exception
        } catch (exception e) {
            system.assert(e.getMessage().contains('Unable to delete'),'Confirm exception');
        }
        
        
    }

    @IsTest 
    public static void deleteUnderlyingStores(){

        Id accId  = [SELECT Id FROM Account WHERE Partner_code__c='MER-CT01' LIMIT 1][0].Id;

        LNAT01_StoreManager.deleteUnderlyingStores(accId);

        List<Integer> recCounters = LNAT01_StoreManager.GetCounters(accId); // result contains: Store, Acceptor, StoreAuth
        system.assertEquals(0, recCounters[0], 'Check Store count');
        system.assertEquals(0, recCounters[1], 'Check Acceptor count');
        system.assertEquals(0, recCounters[2], 'Check StoreAuth count');

        try{
            LNAT01_StoreManager.deleteUnderlyingStores('0010Q00000zzzzzzzz'); //exception
        } catch (exception e) {
            system.assert(e.getMessage().contains('Unable to delete'),'Confirm exception');
        }
    }

    @IsTest 
    public static void deleteUnderlyingAcceptors(){

        Id accId  = [SELECT Id FROM Account WHERE Partner_code__c='MER-CT01' LIMIT 1][0].Id;

        LNAT01_StoreManager.deleteUnderlyingAcceptors(accId);

        List<Integer> recCounters = LNAT01_StoreManager.GetCounters(accId); // result contains: Store, Acceptor, StoreAuth
        system.assertEquals(4, recCounters[0], 'Check Store count');
        
		/* Comment by AAB, error :  System.AssertException: Assertion Failed: Check Acceptor count: Expected: 0, Actual: 4 */
        /* Comment by Kamil adamiec: no idea why this was problematic - TBC after next run */
        
		system.assertEquals(0, recCounters[1], 'Check Acceptor count');
        system.assertEquals(8, recCounters[2], 'Check StoreAuth count');


        try{
            LNAT01_StoreManager.deleteUnderlyingAcceptors('0010Q00000zzzzzzzz'); //exception
        } catch (exception e) {
            system.assert(e.getMessage().contains('Unable to delete'),'Confirm exception');
        }
    }

    @IsTest 
    public static void deleteUnderlyingStoreAuth(){

        Id accId  = [SELECT Id FROM Account WHERE Partner_code__c='MER-CT01' LIMIT 1][0].Id;

        LNAT01_StoreManager.deleteUnderlyingStoreAuth(accId);

        List<Integer> recCounters = LNAT01_StoreManager.GetCounters(accId); // result contains: Store, Acceptor, StoreAuth
        system.assertEquals(4, recCounters[0], 'Check Store count');
        system.assertEquals(4, recCounters[1], 'Check Acceptor count');
        system.assertEquals(0, recCounters[2], 'Check StoreAuth count');

        try{
            LNAT01_StoreManager.deleteUnderlyingStoreAuth('0010Q00000zzzzzzzz'); //exception
        } catch (exception e) {
            system.assert(e.getMessage().contains('Unable to delete'),'Confirm exception');
        }
    }
	
	
	@IsTest 
    public static void additionalTest(){
		LNAT01_StoreManager.additionalTest();

    }
}